### ISSUE TITLE
setting min & max measured values with radialVertical control

### ISSUE THREAD

**Issue by Pierre-Lannoy** [HanSolo/SteelSeries-Canvas#26]
Hello Gerrit and other!
I don't know if it's an omission or something I misunderstood: is it normal that radialVertical doesn't have these methods
* setMinValue
* setMaxValue
* setMinMeasuredValue
* setMaxMeasuredValue

Thanks.
Pierre

**Comment by mcrossley** [comment]
Just an ommission, I'll get it corrected...

**Comment by Pierre-Lannoy** [comment]
Great!

Thanks for all.

**Comment by mcrossley** [comment]
Fixed in v0.14.17
