### ISSUE TITLE
PHP 8.0 or 8.1

### ISSUE THREAD

**Issue by dehatter** [HanSolo/SteelSeries-Canvas#39]
Anyone with the skills looking at making this PHP 8.0 (1) compatible?  Love the looks of the gauges, but I lack any developmental skills necessary to fix it.

Parsererror: Syntax Error: Unexpected end of json input

This set of gauges is used on thousands of weather site all over the world.

![Screenshot 2022-07-17 152201](https://user-images.githubusercontent.com/109482437/179421687-3bd42542-449d-4047-a3d6-ba4416c610d7.jpg)

**Comment by mcrossley** [comment]
I think you have posted on the wrong repository? It looks like you are using the [SteelSeries Weather Gauges](https://github.com/mcrossley/SteelSeries-Weather-Gauges)? That is a separate repo, please repost there and I'll see what I can do.

**Comment by dehatter** [comment]
I posted to the address that is displayed in at the bottom of the gauges.
Apologies if it is the wrong address.

Tom
